### ISSUE TITLE
Question about SSH

### ISSUE THREAD

**Issue by H4sh3** [geerlingguy/docker-centos7-ansible#10]
Hey, first of all great image.
I had some trouble getting it to work, ansible could not connect to the remote host per ssh.
After i installed openssh-clients with yum it worked.
Is the error on my side or should we add the ssh clients lib in the dockerfiles yum install section?
greetings

**Comment by geerlingguy** [comment]
I don't particularly recommend using SSH to either connect to a container, or necessarily inside the container to connect to other things. These images are meant for testing Ansible playbooks, but not necessarily running them against other hosts from within.

In that case, if you need to be able to do that within a container, you'd need to make sure to install the extra software required in your own downstream Dockerfile.
