### ISSUE TITLE
pip not in PATH in python3 tag

### ISSUE THREAD

**Issue by artis3n** [geerlingguy/docker-centos7-ansible#19]
Leveraging `geerlingguy/docker-centos7-ansible:python3`, my Molecule test was failing as pip couldn't be found in the environment. After a little searching, it appears there is a pathing issue in the container:

![image](https://user-images.githubusercontent.com/6969296/162845837-1edc3097-c73a-4ae3-a024-9e133c73de4f.png)

In the `latest` tag, which uses Python 2, pip is correctly linked:

![image](https://user-images.githubusercontent.com/6969296/162845944-0aa121a0-adbe-44fa-a485-b7784629dbd7.png)

One thing to note is the `python3` tag was pushed 2 years ago whereas the `latest` tag was last pushed 4 months ago. https://hub.docker.com/r/geerlingguy/docker-centos7-ansible/tags

https://github.com/geerlingguy/docker-centos7-ansible/blob/master/Dockerfile#L29 was added within the last 10 months, which installs/updates pip, and likely fixes the path resolution as a side effect. I believe the fix would be to pin a `python3` tag with the existing Dockerfile (supplanting python3 for python2). Not sure how that was done 2 years ago, I only see `latest` in CI, so not sure what PR to suggest.

To resolve the error in `geerlingguy/docker-centos7-ansible:python3` as tagged today, I ran `python3 -m pip install -U pip` inside the container and pip was then properly linked.

**Comment by geerlingguy** [comment]
@artis3n - The reason I haven't maintained that python3 tag is apt support is horribly broken under python3 in CentOS 7, therefore any of the projects where I used this container would break if I tried defaulting to python 3 :(

I understand that use case isn't everyone's, but trying to maintain the separate versions was annoying and caused more grief than it was worth for me.

**Comment by artis3n** [comment]
Yeah that's very understandable. No worries!

**Comment by artis3n** [comment]
You're right it's the absolute worst (not working, but for posterity)
https://github.com/artis3n/docker-centos7-ansible-py3
